name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: yarn
      - run: yarn run lint
      # - run: yarn run tsc
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          NODE_OPTIONS: --max_old_space_size=4096
          BUILD_SCRIPT: yarn && npm run site && npm run deploy && git checkout . && git clean -df
