name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: yarn
      - run: npm run site && npm run deploy
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          BRANCH: gh-pages
          FOLDER: dist
       