name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - run: yarn
      - run: yarn run lint
      # - run: yarn run tsc
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          CI: true
          GIT_CONFIG_NAME: chenpan1@sfmail.sf-express.com
          GIT_CONFIG_EMAIL: chenpan1@sfmail.sf-express.com
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'dist/'
          BUILD_SCRIPT: yarn && npm run docs:build && git checkout . && git clean -df
